In [44]:
import pandas as pd

### Import des donnees

In [45]:
# df = pd.read_excel('../data/Boston_Housing.xlsx')

### Enregistrement csv bronze

In [46]:
# df.to_csv('../data/bronze.csv', index=False)

### Nettoyage

In [47]:
df = pd.read_csv('../data/bronze.csv')

CRIM - taux de criminalité par habitant par ville

ZN - proportion des terrains résidentiels zonés pour les terrains de plus de 25 000 pi.ca.

INDUS - proportion d'acres commerciales non commerciales par ville.

CHAS - Variable fictive Charles River (1 si le secteur délimite la rivière ; 0 sinon)

NOX - concentration d'oxydes nitriques (parties par 10 millions)

RM - nombre moyen de pièces par logement

AGE - proportion de logements occupés par leur propriétaire construits avant 1940

DIS - distances pondérées à cinq centres d'emploi de Boston

RAD - indice d'accessibilité aux autoroutes radiales

TAXE - taux d'imposition foncière sur la valeur totale par tranche de 10 000 $

PTRATIO - ratio élèves-enseignant par ville

B - 1000(Bk - 0.63)^2 où Bk est la proportion de noirs par ville

LSTAT - % de statut inférieur de la population

MEDV - Valeur médiane des maisons occupées par leur propriétaire en milliers de dollars

In [48]:
df.rename(columns={'CRIM': 'tx_crim', 'ZN': 'tx_residence', 'INDUS': 'tx_commerce', 'CHAS': 'riviere', 'NOX': 'tx_nitriq', 'RM': 'nb_piece', 'AGE': 'tx_ancienneté_parc_immo', 'DIS': 'distance_centre_emploi', 'RAD': 'proximité_autoroute', 'TAX': 'indice_impot_foncier', 'PTRATIO': 'ratio_eleve_enseignant', 'B': 'tx_person_couleur', 'LSTAT': 'tx_status_sociaux_eco_inf', 'MEDV': 'prix_median'}, inplace=True)

In [49]:
# df['prix_median'] = df['prix_median'].multiply(1000)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   tx_crim                    506 non-null    float64
 1   tx_residence               506 non-null    float64
 2   tx_commerce                506 non-null    float64
 3   riviere                    506 non-null    int64
 4   tx_nitriq                  506 non-null    float64
 5   nb_piece                   506 non-null    float64
 6   tx_ancienneté_parc_immo    506 non-null    float64
 7   distance_centre_emploi     506 non-null    float64
 8   proximité_autoroute        506 non-null    int64
 9   indice_impot_foncier       506 non-null    int64
 10  ratio_eleve_enseignant     506 non-null    float64
 11  tx_person_couleur          506 non-null    float64
 12  tx_status_sociaux_eco_inf  506 non-null    float64
 13  prix_median                506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [51]:
df.describe()

,tx_crim,tx_residence,tx_commerce,riviere,tx_nitriq,nb_piece,tx_ancienneté_parc_immo,distance_centre_emploi,proximité_autoroute,indice_impot_foncier,ratio_eleve_enseignant,tx_person_couleur,tx_status_sociaux_eco_inf,prix_median
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22532.806324
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9197.104087
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5000.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17025.000000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21200.000000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25000.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50000.000000

In [52]:
df.corr()

,tx_crim,tx_residence,tx_commerce,riviere,tx_nitriq,nb_piece,tx_ancienneté_parc_immo,distance_centre_emploi,proximité_autoroute,indice_impot_foncier,ratio_eleve_enseignant,tx_person_couleur,tx_status_sociaux_eco_inf,prix_median
tx_crim,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
tx_residence,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
tx_commerce,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
riviere,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
tx_nitriq,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
nb_piece,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
tx_ancienneté_parc_immo,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
distance_centre_emploi,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
proximité_autoroute,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
indice_impot_foncier,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
ratio_eleve_enseignant,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
tx_person_couleur,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
tx_status_sociaux_eco_inf,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
prix_median,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [53]:
df

,tx_crim,tx_residence,tx_commerce,riviere,tx_nitriq,nb_piece,tx_ancienneté_parc_immo,distance_centre_emploi,proximité_autoroute,indice_impot_foncier,ratio_eleve_enseignant,tx_person_couleur,tx_status_sociaux_eco_inf,prix_median
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24000.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21600.0
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34700.0
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33400.0
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22400.0
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20600.0
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23900.0
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22000.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11900.0

In [54]:
df.to_csv('../data/silver.csv', index=False)