In [18]:
import pandas as pd
from pycaret.regression import *

In [19]:
df = pd.read_csv('../data/gold.csv')

In [20]:
reg_setup = setup(data=df, target='prix_median', train_size=0.8)

In [21]:
best_model = compare_models()

In [22]:
final_model = finalize_model(best_model)

In [23]:
predictions = predict_model(final_model, data=df)

### CatBoost Regressor

In [24]:
model_catboost = create_model('catboost')

In [25]:
tuned_model_catboost = tune_model(model_catboost)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [26]:
evaluate_model(tuned_model_catboost)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

### Gradient Boosting Regressor

In [27]:
model_gbr = create_model('gbr')

Initiated  . . . . . . . . . . . . . . . . . .                     08:45:39
Status     . . . . . . . . . . . . . . . . . .             Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

In [28]:
tuned_model_gbr = tune_model(model_gbr)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [29]:
evaluate_model(tuned_model_gbr)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…